const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('node:path');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const { defaults, validateSettings } = require('../sensor-service');
app.setPath('userData', fs.mkdtempSync('/tmp/pool-ui-test-'));
app.whenReady().then(async () => {
  let win;
  try {
    let settings = defaults();
    settings.sensorTextSize = 40;
    settings.sensorTextWeight = 400;
    settings.secondPulse = false;
    ipcMain.handle('settings:get', () => settings);
    ipcMain.handle('settings:save', (_event, input) => { settings = validateSettings(input); return settings; });
    win = new BrowserWindow({show:false,width:1200,height:800,webPreferences:{preload:path.join(__dirname,'../preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:true}});
    await win.loadFile(path.join(__dirname,'../index.html'));
    const js = code => win.webContents.executeJavaScript(code);
    await new Promise(resolve => setTimeout(resolve, 100));
    assert.equal(await js("getComputedStyle(document.querySelector('.sensor-value')).fontSize"), '40px');
    assert.equal(await js("getComputedStyle(document.querySelector('.tick--current')).animationName"), 'none');
    assert.equal(await js("getComputedStyle(document.querySelector('.sensor-value')).fontWeight"), '400');
    assert.equal(await js("getComputedStyle(document.querySelector('.logo')).filter"), 'grayscale(1)');
    win.webContents.send('sensor:update', {id:'water',status:'ok',value:'+24°'});
    await new Promise(resolve => setTimeout(resolve, 50));
    assert.equal(await js("getComputedStyle(document.querySelector('.logo')).filter"), 'grayscale(1)');
    win.webContents.send('sensor:update', {id:'water',status:'waiting'});
    await new Promise(resolve => setTimeout(resolve, 50));
    assert.equal(await js("getComputedStyle(document.querySelector('.logo')).filter"), 'none');
    await js("document.querySelector('.logo').dispatchEvent(new MouseEvent('click', {bubbles:true}))");
    await new Promise(resolve => setTimeout(resolve, 100));
    assert.equal(await js("document.querySelector('dialog').open"), true);
    await js("document.querySelector('#settings-second-pulse').click()");
    assert.equal(await js("document.documentElement.classList.contains('second-pulse-disabled')"), false);
    await js("document.querySelector('#settings-text-size').value='64'; document.querySelector('#settings-text-size').dispatchEvent(new Event('input'))");
    assert.equal(await js("getComputedStyle(document.querySelector('.sensor-value')).fontSize"), '64px');
    await js("document.querySelector('#settings-text-weight').value='3'; document.querySelector('#settings-text-weight').dispatchEvent(new Event('input'))");
    assert.equal(await js("getComputedStyle(document.querySelector('.sensor-value')).fontWeight"), '700');
    await js("document.querySelector('#settings-address').value='192.168.1.10'; document.querySelector('#settings-form').requestSubmit()");
    await new Promise(resolve => setTimeout(resolve, 100));
    assert.equal(settings.server, 'http://192.168.1.10:8080');
    assert.equal(settings.sensorTextSize, 64);
    assert.equal(settings.sensorTextWeight, 700);
    assert.equal(settings.secondPulse, true);
    await js("document.querySelector('.logo').dispatchEvent(new MouseEvent('click'))");
    await new Promise(resolve => setTimeout(resolve, 50));
    assert.equal(await js("document.querySelector('#settings-text-size').value"), '64');
    await js("document.querySelector('#settings-text-size').value='80'; document.querySelector('#settings-text-size').dispatchEvent(new Event('input')); document.querySelector('#settings-text-weight').value='0'; document.querySelector('#settings-text-weight').dispatchEvent(new Event('input')); document.querySelector('#settings-second-pulse').click(); document.querySelector('#settings-cancel').click()");
    await new Promise(resolve => setTimeout(resolve, 50));
    assert.equal(await js("getComputedStyle(document.querySelector('.sensor-value')).fontSize"), '64px');
    assert.equal(await js("document.querySelector('dialog').open"), false);
    assert.equal(await js("getComputedStyle(document.querySelector('.sensor-value')).fontWeight"), '700');
    assert.equal(await js("document.documentElement.classList.contains('second-pulse-disabled')"), false);
    for (const id of ['outdoor','air','water','humidity']) {
      await js(`document.querySelector('[data-settings="${id}"]').click()`);
      await new Promise(resolve => setTimeout(resolve, 50));
      await js(`document.querySelector('#settings-mode').value='http'; document.querySelector('#settings-mode').dispatchEvent(new Event('change')); document.querySelector('#settings-address').value='${id}'; document.querySelector('#settings-form').requestSubmit()`);
      await new Promise(resolve => setTimeout(resolve, 50));
      assert.equal(settings.sensors[id].endpoint, id);
    }
    await js("document.querySelector('[data-settings=water]').click()");
    await new Promise(resolve => setTimeout(resolve, 50));
    await js("document.querySelector('#settings-mode').value='sse'; document.querySelector('#settings-mode').dispatchEvent(new Event('change'))");
    assert.equal(await js("document.querySelector('#settings-label').textContent"), 'Item name');
    await js("document.querySelector('#settings-address').value='waterTemperature'; document.querySelector('#settings-form').requestSubmit()");
    await new Promise(resolve => setTimeout(resolve, 50));
    assert.deepEqual(settings.sensors.water, { endpoint: 'waterTemperature', mode: 'sse' });
    win.webContents.send('sensor:update', {id:'water',status:'ok',value:'+25°'});
    win.webContents.send('sensor:update', {id:'water',status:'offline'});
    await new Promise(resolve => setTimeout(resolve, 50));
    assert.equal(await js("document.querySelector('[data-sensor=water] .sensor-value').textContent"), '+25°');
    assert.equal(await js("document.querySelector('[data-sensor=water] .sensor-status').textContent"), '');
    assert.equal(await js("getComputedStyle(document.querySelector('.logo')).filter"), 'grayscale(1)');
    win.webContents.send('sensor:update', {id:'air',status:'offline'});
    win.webContents.send('sensor:update', {id:'water',status:'ok',value:'+26°'});
    await new Promise(resolve => setTimeout(resolve, 50));
    assert.equal(await js("getComputedStyle(document.querySelector('.logo')).filter"), 'grayscale(1)');
    win.webContents.send('sensor:update', {id:'air',status:'waiting'});
    await new Promise(resolve => setTimeout(resolve, 50));
    assert.equal(await js("getComputedStyle(document.querySelector('.logo')).filter"), 'none');
    await js("document.querySelector('.logo').dispatchEvent(new MouseEvent('click'))");
    await new Promise(resolve => setTimeout(resolve, 50));
    fs.writeFileSync('/tmp/pool-settings.png', (await win.webContents.capturePage()).toPNG());
    console.log('PASS: logo settings, default port, four endpoints, preserved offline value');
    app.exit(0);
  } catch (error) { console.error(error); app.exit(1); }
});
